import { FollowUpItem, DailyFollowUpRule } from '@/lib/types';

export const MOCK_FOLLOWUPS: FollowUpItem[] = [
  {
    id: "fup-101",
    lead_id: "lead-1",
    lead_name: "Sarah Jenkins",
    company_name: "Acme Enterprise Corp",
    lead_temperature: "WARM",
    sequence_step: 2,
    total_sequence_steps: 4,
    last_contact_date: "2026-07-20",
    next_followup_date: "2026-07-23",
    followup_count: 2,
    status: "Pending Today",
    assigned_user: "Alex Rivers",
  },
  {
    id: "fup-102",
    lead_id: "lead-2",
    lead_name: "Marcus Vance",
    company_name: "Apex CyberSecurity",
    lead_temperature: "HOT",
    sequence_step: 3,
    total_sequence_steps: 4,
    last_contact_date: "2026-07-22",
    next_followup_date: "2026-07-23",
    followup_count: 3,
    status: "Escalated to HOT",
    assigned_user: "Alex Rivers",
  },
  {
    id: "fup-103",
    lead_id: "lead-3",
    lead_name: "Elena Rostova",
    company_name: "FinPulse Financial AI",
    lead_temperature: "HOT",
    sequence_step: 1,
    total_sequence_steps: 4,
    last_contact_date: "2026-07-21",
    next_followup_date: "2026-07-24",
    followup_count: 1,
    status: "Response Received",
    assigned_user: "Sarah Connor",
  },
  {
    id: "fup-104",
    lead_id: "lead-4",
    lead_name: "David Chen",
    company_name: "BioHealth Diagnostics",
    lead_temperature: "COLD",
    sequence_step: 1,
    total_sequence_steps: 4,
    last_contact_date: "2026-07-16",
    next_followup_date: "2026-07-23",
    followup_count: 1,
    status: "Scheduled",
    assigned_user: "David Kim",
  },
];

export const DAILY_RULES: DailyFollowUpRule[] = [
  {
    id: "rule-1",
    rule_name: "Scheduled Day Sequence Trigger",
    condition: "Next follow-up date == Today AND Status == Scheduled",
    action: "Send automated sequence step email & update last contact date",
    active: true,
  },
  {
    id: "rule-2",
    rule_name: "Response Received Sequence Halt",
    condition: "Email opened with reply OR meeting booked",
    action: "Stop automated sequence, flag lead as Response Received, notify assigned rep",
    active: true,
  },
  {
    id: "rule-3",
    rule_name: "Hot Lead Temperature Escalation",
    condition: "Reply contains high-intent keywords ('demo', 'pricing', 'call')",
    action: "Escalate temperature to HOT, set priority task, update lead stage",
    active: true,
  },
  {
    id: "rule-4",
    rule_name: "Task Reminder Generation",
    condition: "No response after Step 3 follow-up (7 days elapsed)",
    action: "Create phone call task for assigned rep with call script preview",
    active: true,
  },
];
