import { NotificationItem } from '@/lib/types';

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-301",
    type: "New hot lead",
    title: "🔥 New HOT Lead Escalation!",
    message: "Elena Rostova (FinPulse AI) replied requesting pricing details. Lead score updated to 96/100.",
    timestamp: "10 minutes ago",
    read: false,
    priority: "urgent",
    action_url: "/leads",
    related_entity: { type: "lead", name: "Elena Rostova", id: "lead-3" },
  },
  {
    id: "notif-302",
    type: "Reply received",
    title: "✉️ Email Reply Received",
    message: "Marcus Vance (Apex CyberSecurity) opened email and replied: 'Can we schedule a call tomorrow?'",
    timestamp: "32 minutes ago",
    read: false,
    priority: "high",
    action_url: "/outreach",
    related_entity: { type: "lead", name: "Marcus Vance", id: "lead-2" },
  },
  {
    id: "notif-303",
    type: "Follow-up due",
    title: "⏰ Follow-Up Scheduled Today",
    message: "Step 2 follow-up email is scheduled for Sarah Jenkins (Acme Enterprise Corp) at 02:00 PM.",
    timestamp: "1 hour ago",
    read: false,
    priority: "medium",
    action_url: "/follow-up",
    related_entity: { type: "lead", name: "Sarah Jenkins", id: "lead-1" },
  },
  {
    id: "notif-304",
    type: "Task overdue",
    title: "⚠️ Overdue Task Alert",
    message: "Phone call task for David Chen (BioHealth Diagnostics) is 24 hours overdue.",
    timestamp: "3 hours ago",
    read: true,
    priority: "urgent",
    action_url: "/tasks",
    related_entity: { type: "task", name: "Call David Chen", id: "task-204" },
  },
  {
    id: "notif-305",
    type: "Campaign completed",
    title: "🎉 Campaign Completed",
    message: "'Q3 CTO Enterprise Outreach' completed sequence execution (1,420 emails sent, 18.2% reply rate).",
    timestamp: "Yesterday",
    read: true,
    priority: "low",
    action_url: "/campaigns",
    related_entity: { type: "campaign", name: "Q3 CTO Enterprise Outreach", id: "camp-1" },
  },
];
